import type { DealEvent, DealInfo } from './deal.types';

export const mockDeal: DealInfo = {
    id: 6,
    stage: 'installation',
    clientName: 'Козлова Марина Игоревна',
    phone: '+7 (999) 000-11-22',
    address: 'г. Москва, ул. Ленина, д. 42, кв. 15',
    passport: '4510 123456, выдан ОВД Центрального района г. Москвы, 15.03.2010',
    source: 'Яндекс.Директ',
    responsibleManager: 'Сидоров Алексей Петрович',
    dealSum: 48500,
    measurerName: 'Иванов Сергей Николаевич',
    measurementDate: '01.04.2026, 10:00',
    installerName: 'Орлов Михаил Дмитриевич',
    installationDate: '06.04.2026, 15:30',
    createdAt: '29.03.2026, 08:50',
};

export const mockEvents: DealEvent[] = [
    {
        id: 1,
        type: 'status_change',
        fromStatus: '—',
        toStatus: 'Новое обращение',
        changedBy: 'Система',
        timestamp: '29.03.2026, 08:50',
    },
    {
        id: 2,
        type: 'status_change',
        fromStatus: 'Новое обращение',
        toStatus: 'Созвон с клиентом',
        changedBy: 'Сидоров Алексей Петрович',
        timestamp: '29.03.2026, 11:30',
    },
    {
        id: 3,
        type: 'status_change',
        fromStatus: 'Созвон с клиентом',
        toStatus: 'Назначен замер',
        changedBy: 'Сидоров Алексей Петрович',
        timestamp: '30.03.2026, 09:15',
    },
    {
        id: 4,
        type: 'measurement',
        measurerName: 'Иванов Сергей Николаевич',
        measurementDate: '01.04.2026, 10:00',
        timestamp: '30.03.2026, 09:16',
    },
    {
        id: 5,
        type: 'comment',
        authorName: 'Сидоров Алексей Петрович',
        text: 'Клиент хочет матовый потолок в зал и глянцевый в спальню. Уточнить цвет при замере.',
        timestamp: '30.03.2026, 09:20',
    },
    {
        id: 6,
        type: 'attachment',
        fileType: 'image',
        fileName: 'замер_зал_фото1.jpg',
        comment: 'Фото помещения после замера',
        timestamp: '01.04.2026, 11:45',
    },
    {
        id: 7,
        type: 'status_change',
        fromStatus: 'Назначен замер',
        toStatus: 'Отправлено в производство',
        changedBy: 'Сидоров Алексей Петрович',
        timestamp: '01.04.2026, 14:00',
    },
    {
        id: 8,
        type: 'attachment',
        fileType: 'pdf',
        fileName: 'Договор_№6_Козлова.pdf',
        timestamp: '01.04.2026, 14:10',
    },
    {
        id: 9,
        type: 'materials',
        items: [
            { id: 1, name: 'Полотно матовое белое 3.2м', quantity: 12, unit: 'м²' },
            { id: 2, name: 'Полотно глянцевое белое 2.8м', quantity: 9, unit: 'м²' },
            { id: 3, name: 'Багет стеновой ПВХ', quantity: 28, unit: 'м' },
            { id: 4, name: 'Дюбель-гвозди 6×30', quantity: 120, unit: 'шт' },
            { id: 5, name: 'Саморезы 40мм', quantity: 0.2, unit: 'кг' },
            { id: 6, name: 'Платформа под светильник', quantity: 6, unit: 'шт' },
            { id: 7, name: 'Термокольцо 60мм', quantity: 6, unit: 'шт' },
        ],
        timestamp: '02.04.2026, 10:30',
    },
    {
        id: 10,
        type: 'status_change',
        fromStatus: 'Отправлено в производство',
        toStatus: 'Назначен монтаж',
        changedBy: 'Сидоров Алексей Петрович',
        timestamp: '03.04.2026, 09:00',
    },
    {
        id: 11,
        type: 'installation',
        installerName: 'Орлов Михаил Дмитриевич',
        installationDate: '06.04.2026, 15:30',
        timestamp: '03.04.2026, 09:05',
    },
];
